springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-param-without-oauth2: true

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  security:
    oauth2:
      client:
        registration:
          google:
            client-id : 66553669104-j9vtrudrf6r90bt4t4tmaptfaemsomvt.apps.googleusercontent.com
            client-secret : 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


  devtools:
    liveload:
      enabled =true

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:project
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    secret : secretcarrot
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    defer-datasource-initialization: true
  profiles:
    active: true



logging:
  level:
    me.silvernine: DEBUG


server:
  port: 8001